feat: takes into account when statics not in host_url root
nickjj/flask-static-digest pull request #22
Opened 2021-06-05 22:19 UTC by ybenitezf

Closes #21

2021-06-06 11:55 UTC, nickjj commented
Hi,

Thanks, I haven't gotten a chance to test it locally but does this work when `FLASK_STATIC_DIGEST_HOST_URL` is `None` which is the default when you don't set it? Also, for `parse_digest_host_url`, was it necessary to return a tuple there? What happens if you return everything together which is then used in `_prepend_host_url`?

2021-06-06 18:37 UTC, ybenitezf commented on tests/test_static_url_for.py
> +        (None, '/mystatic/url', "hey.png", "/mystatic/url/hey-HASH.png"),
This two cases are for when the variable or `static_url_path` are not set.

2021-06-06 18:40 UTC, ybenitezf commented
> ... Also, for `parse_digest_host_url`, was it necessary to return a tuple there? What happens if you return everything together which is then used in `_prepend_host_url`?

I just wanted to test this separately. Also, It seemed to me that I should not mix `parse_digest_host_url` with the code in the class. But yea, i could do as you say, let me know if a fix is needed for this.

2021-06-07 19:05 UTC, nickjj commented
Will have to think about that one a bit. Just replying to acknowledge your response. Since it's the work week now I'm a little slammed, but I want to let you know this will for sure get merged in 1 way or another.

2021-07-10 21:05 UTC, ybenitezf commented
@nickjj  ¿any progress with this?

2021-07-10 23:54 UTC, nickjj requested changes
Sorry, I've left a few comments. Let me know what you think.

2021-07-10 23:54 UTC, nickjj commented on flask_static_digest/__init__.py
> +    the elements (host_part, path_part), for example for
Can you re-word this line to be:

`the elements (host_part, path_part), for example:`

2021-07-10 23:54 UTC, nickjj commented on flask_static_digest/__init__.py
> +    This function should return:
Can you change this line to:

`This function will return results such as:`

2021-07-10 23:54 UTC, nickjj commented on flask_static_digest/__init__.py
> +    ('https://cdn.example.com', "/myapp/some/path/")
Can you change this line into these lines:

```
# When there's no path:
('https://cdn.example.com')

# When there's a path:
('https://cdn.example.com', '/my/custom/path/')
```

2021-07-10 23:54 UTC, nickjj commented on flask_static_digest/__init__.py
> +def parse_digest_host_url(host_url_prefix):
Can you rename this function to `_parse_digest_host_url` since it's private?

2021-07-10 23:54 UTC, nickjj commented on flask_static_digest/__init__.py
> +        parts = list( # removing empty strings
Any chance we can write rewrite this and the line below it to be a more clear on what it does?

2021-07-10 23:54 UTC, nickjj commented on tests/test_parse_digest_host_url.py
> +from flask_static_digest import parse_digest_host_url
Thoughts on replicating all of these tests without using pytest, following the same patterns used in the existing test suite?

2021-07-16 12:17 UTC, nickjj commented
I'm beginning to think this PR along with `FLASK_STATIC_DIGEST_HOST_URL` might not even be needed due to a new recent discovery. I always set Flask's `static_url_path` to `""` in development but it just dawned on me that you could very likely set that to `https://cdn.example.com/whatever/you/want"` and Flask will prefix your URLs with that.

That completely negates needing `FLASK_STATIC_DIGEST_HOST_URL`.

What do you think?

2021-07-16 15:40 UTC, ybenitezf commented
> I'm beginning to think this PR along with `FLASK_STATIC_DIGEST_HOST_URL` might not even be needed due to a new recent discovery. I always set Flask's `static_url_path` to `""` in development but it just dawned on me that you could very likely set that to `https://cdn.example.com/whatever/you/want"` and Flask will prefix your URLs with that.
> 
> That completely negates needing `FLASK_STATIC_DIGEST_HOST_URL`.
> 
> What do you think?

It depends on if it works, have you tested ? i don't have time right now, if u think that work ok, u should update the README.md and close this PR.

2021-07-16 16:04 UTC, nickjj commented
I haven't tested it yet but I will in the next couple of days.

If it works I'll update the readme and ship a new version with that option removed along with adding new docs to go over how to do the same thing with Flask's built in `static_url_path`.

2021-07-16 23:30 UTC, nickjj commented
Nope, it doesn't work. `static_url_path` requires a URL that starts with a `/` so putting in a hostname with a protocol doesn't work.

Which means the option and this PR is still going to be a good idea.

2021-07-18 02:32 UTC, ybenitezf commented
> Nope, it doesn't work. `static_url_path` requires a URL that starts with a `/` so putting in a hostname with a protocol doesn't work.
> 
> Which means the option and this PR is still going to be a good idea.

Have you see this parameters on [the flask object](https://flask.palletsprojects.com/en/2.0.x/api/#application-object): `static_host` and `host_matching` in together with `static_url_path` and `static_folder` in Flask 2.x.x ? I think that can do the trick, don't remember those from previous versions.

2024-05-17 15:55 UTC, nickjj commented
This has been resolved in: https://github.com/nickjj/flask-static-digest/pull/38

2024-05-17 15:55 UTC, closed without merging